data/global/excel/treasureclassex.txt

* Reduce amount of drops in Normal Mode in general
* Reduce the amount of gold dropped drastically

Treasure class stuff

---

data/global/ui/layouts/controller/_profilehd.json
data/global/ui/layouts/controller/advancedstatspanelhd.json
data/global/ui/layouts/controller/bankexpansionlayouthd.json
data/global/ui/layouts/controller/bankoriginallayouthd.json
data/global/ui/layouts/controller/characterstatspanelhd.json
data/global/ui/layouts/controller/controlleroverlayhd.json
data/global/ui/layouts/controller/hudmonsterhealthhd.json
data/global/ui/layouts/controller/hudpanelhd.json
data/global/ui/layouts/controller/imbueitemspanelhd.json
data/global/ui/layouts/controller/pauselayouthd.json
data/global/ui/layouts/controller/pc/hudmonsterhealthhd.json
data/global/ui/layouts/controller/playerinventoryexpansionlayouthd.json
data/global/ui/layouts/controller/playerinventoryoriginallayouthd.json
data/global/ui/layouts/controller/questlogpanelexpansionhd.json
data/global/ui/layouts/controller/questlogpaneloriginalhd.json
data/global/ui/layouts/controller/skillstreepanelhd.json
data/global/ui/layouts/controller/uiswitcherhd.json
data/global/ui/layouts/controller/waypointspanelexpansionhd.json
data/global/ui/layouts/controller/waypointspaneloriginalhd.json
data/hd/global/ui/controller/hud/monsterhealth/monsterhealth_console.lowend.sprite
data/hd/global/ui/controller/hud/monsterhealth/monsterhealth_console.sprite
data/hd/global/ui/controller/panel/spells/v2/centerpanelbg_skilltrees.lowend.sprite
data/hd/global/ui/controller/panel/spells/v2/centerpanelbg_skilltrees.sprite
data/hd/global/ui/controller/panel/spells/v2/skilltreeextra.lowend.sprite
data/hd/global/ui/controller/panel/spells/v2/skilltreeextra.sprite

Woof figuring it out. Controller UI rework to be similar to PC ui

controller ui rework

---

data/local/lng/strings/item-names.json

Resolves: #106 
Fixes an item showing An Evil Force

fix: adamantine links unique item name showing an evil force

---

data/global/excel/cubemain.txt

Socket Punch Fox Again

---

data/global/excel/treasureclassex.txt

* Reduces number of corruption orbs dropped from cowking

fix: cowking dropping insane amount of corruption orbs

---

data/local/lng/strings/item-names.json

Updated the files to be in line with the changes made to the next branch with the addition of the PR **_Addition: Added quality Indicator to Item names #168_**

Addition: Item quality indicator

---

data/local/lng/strings/item-names.json

Rat Lords Curse, Blanched Death string fixes

---

data/global/excel/uniqueitems.txt

Updates uniqueitems.txt key to match item-names.json key

Rat Lords Curse

---

data/global/excel/runes.txt
data/local/lng/strings/item-runes.json

Solves the Issue #206
- Changed the first column "Name" to the actual name of the runeword to match the setup for uniques and sets.
- Changed some runeword names, just minor changes like "Fortune" to "Fortune's Favor" and "Morning" to "Morning Dew"

Uniform file format

---

data/global/excel/uniqueitems.txt

- resolves #218
- unintended change from nolimit adjustments caused 3 torch uber tristram runs

restored hellfire torch nolimit

---

data/global/ui/layouts/modcube_aahd.json
data/global/ui/layouts/modcube_typechanginghd.json
data/global/ui/layouts/modinfo_generalinformationhd.json

- wiki link added
- changed tilte to Type Chaning & Corruption
- Added Orb of Conversion info
- Added Corruption Orb info

Final update to custom menus for 1.21

---

data/local/lng/strings/item-names.json

By removing color tags from [N/X/E]

Fix gray item names on uniques/sets

---

data/hd/character/player/barbarian/barbarian_state_machine.json

Changed WarCry to use Cast Animation

---

data/global/excel/itemstatcost.txt

feat: increase the amount of gems you can have in gembag

---

data/global/excel/treasureclassex.txt

chore: update droptables for countess

---

data/global/excel/uniqueitems.txt

Fix Rainbow Facet string

---

data/global/excel/uniqueitems.txt

Whitespace at the end of item name

String Fix

---

data/hd/global/ui/controller/panel/spells/v2/SkillTreeExtra_Edit.lowend.sprite
data/hd/global/ui/controller/panel/spells/v2/SoSkilltree_Edit.lowend.sprite
data/hd/global/ui/panel/goldbutton.lowend.sprite
data/hd/global/ui/panel/horadric_cube/transmutebutton.lowend.sprite
data/hd/global/ui/panel/options/breakpointsbg.lowend.sprite
data/hd/global/ui/panel/stash/stash_tabs2.lowend.sprite
data/hd/global/ui/panel/waypoints/waypoints_background.lowend.sprite
data/hd/global/ui/panel/waypoints/waypoints_button.lowend.sprite
data/hd/global/ui/panel/waypoints/waypoints_button_active.lowend.sprite
data/hd/global/ui/panel/waypoints/waypoints_button_disabled.lowend.sprite
data/hd/global/ui/panel/waypoints/waypoints_tab.lowend.sprite
data/hd/global/ui/spells/amazon/amskillicon.lowend.sprite
data/hd/global/ui/spells/assassin/asskillicon.lowend.sprite
data/hd/global/ui/spells/barbarian/baskillicon.lowend.sprite
data/hd/global/ui/spells/druid/drskillicon.lowend.sprite
data/hd/global/ui/spells/necromancer/neskillicon.lowend.sprite
data/hd/global/ui/spells/paladin/paskillicon.lowend.sprite
data/hd/global/ui/spells/skill_trees/baskilltree.lowend.sprite
data/hd/global/ui/spells/sorceress/soskillicon.lowend.sprite

Resolves: #331
Couldn't figure out how to separate all the changes in the prior branch I had (It looked like it wanted to just removed the druid skill trees entirely from next and don't want that); So I just remade it and knocked out the files that were changed to make the .lowend variants.

Issue 331 Fix

---

data/global/excel/cubemain.txt

3 Ammy = Ammy atm, this changes it to ring.

Rare Reroll Fix

---

data/global/excel/magicprefix.txt
data/global/excel/magicsuffix.txt
data/global/excel/runes.txt
data/global/excel/sets.txt
data/local/lng/strings/item-nameaffixes.json

- Fixed reference to wrong bases from boots > boot and staff > staf in a couple of spots.
- Cleaned up a couple of capitalization errors in item properties
- Added bone spear projectile affix name.

Minor Cleanup

---

data/hd/global/ui/controller/panel/spells/v2/baskilltree.lowend.sprite
data/hd/global/ui/controller/panel/spells/v2/baskilltree.sprite
data/hd/global/ui/controller/panel/spells/v2/drskilltree.lowend.sprite
data/hd/global/ui/controller/panel/spells/v2/drskilltree.sprite

Updates trees to reflect current 2.0 changes to both classes.

Barb and Druid Tree in Controller UI

---

data/global/excel/cubemain.txt
data/global/ui/layouts/characterselectpanelhd.json

Changed the recipe to use base item's item level for the output item level to prevent socket number cheesing early to mid game.
Updates character select to show the proper preview build #

Updated White Convert iLvl - Updated C Select Build #

---

data/global/excel/treasureclassex.txt

Countess Rune Item 3 field populated for all 6 entries but the Prob 3 field was not.

Added Missing Prob for Item 3

---

data/global/excel/automagic.txt

Updates Automagic rare column for 317 with a 1, also added a 1 to rare for 38 as it should've had one.

Fix Charm Weight on Throwing Weapons

---

data/global/excel/uniqueitems.txt

-DS/lvl changes to flat DS as intended in the item rebalance patch

Shattering Blow - DS/lvl to DS

---

data/local/lng/strings/item-names.json

MissingString-OrbofInfusion

---

data/global/excel/monprop.txt

- Level of curses cast by mummy on death have been lowered. Lower Res was a bit of an issue at -55res

Mummy Nerf

---

data/global/excel/cubemain.txt

- Corrected the Reroll Magic Item recipe utilizing 3 perfect gems
Note: Verified a single grand charm reroll

Reroll Magic Pgem Recipe Fix

---

data/local/lng/strings/ui.json

Resolves: #429 
ID conflict between 27203 movetobelt vanilla and 27203 mod InventoryItemTooltipAppenderCtrlUnequip (Merc unequip string.)

Update ID to resolve Missing String

---

data/local/lng/strings/monsters.json

- Thresh Socket has his name back

StringFix-ThreshSocket

---

data/global/excel/runes.txt

- Darkness runeword will now roll all its properties again

Bugfix-DarknessRuneword

---

data/global/excel/sets.txt

Fixes #524
Set bonus all-res changed to fixed 10/25/40

Tika's Request Set Bonus

---

data/global/excel/magicsuffix.txt

this was reverted by the charm rework PR/commits.

revert freq back to 64

---

data/global/ui/layouts/breakpointspanelhd.json

add mf section to breakpoints

---

data/local/lng/strings/item-names.json

- Missing languages were breaking the .jsons for several languages

LanguageFix

---

data/global/excel/itemtypes.txt

Made it so you can't buy back stacked orbs

OrbStackBug

---

data/global/excel/superuniques.txt

- Raven's Talon and Raven's Eye will now only spawn once

RavenTalon-DuplicateSpawns

---

data/global/excel/uniqueitems.txt
data/hd/character/enemy/flyingscimitar.json

set to 1.8, could maybe be lowered to 1.5 ish. 2.0 seems maybe a tad too big.
unable to scale the particle from my limited testing.

add flying scim json to adjust scale of swords

---

data/global/ui/layouts/controller/imbueitemspanelhd.json

Duriel Window Fix Controller

---

data/global/ui/layouts/characterselectpanelhd.json

Updates version text to 2.0.5 and vertically centers it in the border.

Update Version Text

---

data/global/ui/layouts/characterselectpanelhd.json

update version text to 2.1.0, this same element is pulled by controller ui so doesn't need updating there.

version update

---

data/global/excel/sounds.txt

Re-added sound compounding delay to both multiple shot missiles and thankfully, thankfully, it no longer plays at 4x volume while shooting.
Also added 3D spread back to ice shatter and punch because they both go too hard when standing close.

MS Sound Bug/Ice Blurgsh

---

data/local/lng/strings/skills.json

it's discussed on discord.
only Korean translation apply this changes.

Refix `warp` Kor translation

---

data/global/excel/itemtypes.txt

add staff mods to all sin weapons

Assassin Staff Mods
