D2R-Reimagined/d2r-reimagined-mod

data/global/excel/uniqueitems.txt
Grim Ward is a dead skill. Replaced with Deadly Treasures since it replaced GW on the skill tree.
=> Heartcarver - Replace Grim Ward with Deadly Treasures

.gitignore
Adding ignore pngs to gitignore so we don't accidently upload sprite conversions
=> chore: add png files to gitignore

data/global/excel/treasureclassex.txt
* Reduces the drop chance of conversion orbs by half
* Hopefully fixes terror duriel not dropping anything
* Hopefully fixes terror andy not dropping anything
* Several mobs had incorrect gold droptables. These have been resolved. Things not dropping gold before should now
=> chore: reduce chance of conversion orbs by half

data/global/excel/uniqueitems.txt
- Set "nolimit" for all uniques to 1 to enable uniques appearing multiple times in the same session to make it harder to min/max for specific uniques with the new Orb of Conversion or for example gambling.
- Set "lvl" to an appropriate value in relation to "lvl req" to reduce the drop chance of high level items by the item not dropping from low level enemys. This was somewhat regulated by the base items _lvl_ inside _armor.txt_ and _weapon.txt_ but with this change it is made sure.
=> Unique changes

data/global/ui/layouts/bankexpansionlayouthd.json, data/global/ui/layouts/horadriccubelayouthd.json, data/global/ui/layouts/playerinventoryoriginallayouthd.json, data/hd/global/ui/panel/goldbutton.sprite, data/hd/global/ui/panel/horadric_cube/transmutebutton.sprite
QoL for the lazy and imprecise folk on PC.
Added 20% larger Transmute button for Cube and moved it closer to the inventory screen. Now it's easier to click.
Moved the X (exit) button of cube slightly to the left so now it is part of it's own UI like other X buttons.
Added 25% larger Gold button, adjusted it's positions. It is easier to click now.
Button images were upscaled via AI.
=> Gold & Transmute button QoL + Cube X button moved

data/global/ui/layouts/controller/bankexpansionlayouthd.json
_This is a rehash/cleanup of #203 (sorry for the mess)_
-----
On taller resolutions (closer to a 1:1 ratio) the Stash/Bank is cut off on the left side, when using a controller. I first noticed this on the Steam Deck as it has a relatively taller native resolution (1280x800). However, my proposed change here should fix it for the Steam Deck and other devices with more "square" resolutions (old monitors, and handheld devices). Moreover, it will make it easier to move items around (where the player's stash and inventory are side-by-side).
From my testing, my proposed  works well with any resolution (but I only tried a few):
- 3840x2160
- 2560x1440
- 1280x960 (Very square; but still visible ...  barely. _Side note: there's plenty of room to the right of the player inventory, the whole thing …
=> Fix stash tab getting cut off on Steam Deck (and other tall resolutions)

data/global/excel/runes.txt
This EoL/Null/End of FIle character is a big red flag
=> Fixed Snowdrop

data/hd/global/ui/items/misc/potion/lesser_healing_potion.lowend.sprite, data/hd/global/ui/items/misc/potion/lesser_healing_potion.sprite, data/hd/global/ui/items/misc/potion/lesser_mana_potion.lowend.sprite, data/hd/global/ui/items/misc/potion/lesser_mana_potion.sprite
The lesser_potions sprite looked out of place, too bright. Adjusted brightness and contrast values ​​to match the rest of the potions.
Actual
Modified (darker)
=> Match lesser potions sprites

data/hd/global/ui/spells/skill_trees/drskilltree.lowend.sprite, data/hd/global/ui/spells/skill_trees/drskilltree.sprite
Just removed the arrows from the Druid skill tree in order to remove prereq skills across the board. The purpose is to clear up the travel points to have more overall skill points be available to each class.
=> Druid Skill Tree Update

data/global/excel/uniqueitems.txt
There is a whitespace after Spikethrower in uniqueitems.txt
Credits to Delegus
=> Spikethrower Missing String

data/global/ui/layouts/_profilehd.json
1.21.1 - 2.0 Preview causing blz-log.text error "Cannot find JSON reference ($SkillHotkeyTextAltStyle)" so investigated and the entire reference for the skill row icon bar thing was missing so D2 was tossing default there and it wasn't compatible with the old _profilehd.json which used multiple workaorunds to at least show some kind of key. I got it working at 1080P and doesn't alter controller layout/behavior; Could someone test with a higher resolution monitor for me?
Edit: Screenshots on my most hot keyed character; Have tested on others using spacebar (Space) numpad keys (Show up as Num0-9) and shift and looks fine. Dropshadow changed to no transparency but can dial it back to default 200 of 255 if it is too glaring.
=> Skill Hotkeys

data/global/excel/experience.txt, data/global/ui/layouts/controller/horadriccubelayouthd.json
Updates overall level cap to 100 for all classes. (Save Breaking?)
Moves the controller cube transmute button into a more sensible location.
=> Level 100 Cap - Controller Cube Button

data/global/excel/itemstatcost.txt, data/global/excel/uniqueitems.txt
Updates Life & Death Large Charm to only have 2 weight instead of 4.
Updates mana_control to point at mana versus maxmana so that items with max mana % modifiers do not break the system.
=> Updates to Weight System

data/global/excel/treasureclassex.txt
The class "Conversion Orbs" needs to be above the classes that are trying to nest from it, relocated above Jewelry so these orbs will properly drop.
=> Conversion and Assemblage Drop Fix

data/global/excel/itemstatcost.txt
Fixes weight system, not save breaking. Should be merged and the preview 3 .7z updated, maybe after drop rate changes are also fixed.
=> Weight Refix after Gem Merge

data/global/excel/magicprefix.txt, data/global/excel/uniqueitems.txt
- Tectonic Slam charges will no longer spawn on non-Slam weapons
- Poison Dagger charges will no longer spawn on non-Knife weapons
- "Epee of Speed" unique now has charges of Concentrate instead of Stun/Tectonic Slam as it is not a slam weapon
Note: Double check recent keychain/gembag change was not blown out
=> WeaponDependentSkills

data/global/excel/magicsuffix.txt, data/local/lng/strings/item-nameaffixes.json
- Added missing string "of the Lich"
- Boosted chance to roll +Bone Spear and +Holy Bolt affixes.
=> Missing String

data/hd/global/excel/desecratedzones.json
Fixes #523 
Terror Zone entries are now in order.
Added new Terror Zones now that level cap is 25 (up from 20).
Act1 - Burial Grounds, Crypt, Mausoleum (24 zones total)
Act2 - Stony Tomb (all levels), Ancient Tunnels (22 zones total)
Act 3 - Spider Forest, Great Marsh, Arachnid Lair, Spider Cavern, Flayer Dungeon Level 3, Ruined Temple, Disused Fane (22 zones total)
Act 5 - Drifter Cavern, Frozen Tundra, Infernal Pit (22 zones total)
=> Expanding terror zones in Acts1/2/3/5

data/hd/global/ui/spells/barbarian/baskillicon.lowend.sprite, data/hd/global/ui/spells/barbarian/baskillicon.sprite
Updates new Barbarian skill Tectonic Slam with a sprite made for it.
=> Tectonic Slam Icon

data/global/ui/layouts/controller/waypointspanelexpansionhd.json, data/global/ui/layouts/controller/waypointspaneloriginalhd.json, data/global/ui/layouts/waypointspanelexpansionhd.json, data/global/ui/layouts/waypointspaneloriginalhd.json, data/hd/global/excel/desecratedzones.json, data/hd/global/ui/panel/waypoints/terror_zone_icon.lowend.sprite, data/hd/global/ui/panel/waypoints/terror_zone_icon.sprite, data/hd/global/ui/panel/waypoints/waypoints_button.lowend.sprite, data/hd/global/ui/panel/waypoints/waypoints_button.sprite, data/hd/global/ui/panel/waypoints/waypoints_button_active.lowend.sprite, data/hd/global/ui/panel/waypoints/waypoints_button_active.sprite
Waypoint button sprites updated so that when you click them there is an animation and the icons and text no longer disappear.
- Nothing selected
- Spider Forest Selected (Can't SS cursor in sadly.)
WPs updated to include Terror Zone Icon and Text coloring to indicate Terror Zone
- Redundant I know, but Alice and her white rabbit beckoned, it's a simple flag change to disable if unpopular.
- Created a Terror Zone Sprite out of the Vanilla sprite to match our waypoint icon.
desecratedzones.json re-ordered so that zones are displayed in order by adjacency to other zones instead of by level ID.
- Multiple waypoint ID's added/fixed in order to make the shiny new sprite and text work.
- Den of evil replaced by Dark Woods because Den was lonely and didn't make sense.
- Black Marsh re-added cause …
=> WP UI Animated And More TZ Updates

data/global/excel/sets.txt
fixes issue https://github.com/D2R-Reimagined/d2r-reimagined-mod/issues/535
switched oskill to skill, and capitalized skill names because it matter/crashes the game otherwise.
22 werewolf before set bonus
30 after
=> switching for oskill to skill for druid specific set

data/global/ui/layouts/vendorpanellayouthd.json
This update removes the Yes/No confirmation from vendor panels, it just autoselects yes with no delay so you can fill your inventory with a left click macro with potions/gambling, etc.
Side Effects: Removes "Not Enough Gold" from buying items or repairing as a clickable confirmation but it is pretty obvious when a vendor action fails due to a lack of gold. Item doesn't appear in inventory, repair doesn't happen and Repair All cost stays the same.
https://github.com/user-attachments/assets/06b67faa-568c-49e1-a117-617e74718908
=> Vendor Panel Confirm Removal

data/local/lng/strings/item-names.json
- Winged Helm now correctly shows [X] as it is an Exceptional quality base
=> Updated Winged Helm to Exceptional

data/global/excel/uniqueitems.txt
- Reworked some under performing unique jewels 
- Previously rolled 15-20% ED, 5-8 Max Damage
- Now rolls 40% ED, 15 Min Damage, 5-8% Deadly Strike 
- Previously rolled 20-29 %ED, 8-10 Max Damage
- Now rolls 40% ED, 15 Max Damage, 5-8% Crushing Blow 
- Previously rolled 25% Gold Find, 10-15% Magic Find, 25-50 Defense
- Now rolls +1-140 Lightning Weapon Damage, 24-28% Magic Find, 25-35% Lightning Resist, +1% Max Lightning Resist 
- Previously rolled 27-34% ED, 15% IAS
- Now rolls +3-5% Increased Poison Skill Damage, +10-15 Dexterity, +25-35% Poison Resist, +1% Max Poison Resist 
- Previously rolled 37-40% ED, 15% IAS
- Now rolls +60-80 Cold Weapon Damage, +35-40 Mana, +2% Maximum Mana, +25-35% Cold Resist, +1% Max Cold Resist 
- Previously rolled +37-40% ED, +12-15 Max Damage
- Now rolls …
=> Unique-Jewels-Rework

data/global/excel/magicsuffix.txt
Fixes #664
Magic Suffix 'Of Traveling' gives stam drain reduction in addition to FRW. Without this affix its just a copy of the suffix 'Of Speed' with a higher level requirement. Disabling this as a spawnable affix.
=> 'Slower Stamina Drain' Rollable Affix

data/global/excel/properties.txt
oskill with a range are currently rolling seperate values for the display string and the actual value given. This corrects that.
This fix is not retroactive, runewords such as CTA will need to be re-created, items such as Hellhunger will need to be refound in order for the correct +skill to display.
=> oksill Value Fix

data/hd/global/ui/spells/submenu/skillicon.lowend.sprite, data/hd/global/ui/spells/submenu/skillicon.sprite
Update default game icons to be in line with Reimagined Icon art.
=> Default skill icons

data/global/excel/states.txt
So after some tracking of the beam itself it is added to all the player model corpses to make finding them easier.
The decoy is a duplicate of the amazon and thus also received said beam on death.
Flagging the state as hidedead solves the problem.
=> Fix Decoy Perma-Beam

data/local/lng/strings/item-modifiers.json, data/local/lng/strings/item-names.json, data/local/lng/strings/item-runes.json, data/local/lng/strings/skills.json
This PR improves the Simplified Chinese (zhCN) and Traditional Chinese (zhTW) translations in the localization files of the D2R Reimagined Mod.
- Improved translation accuracy and fluency
- Corrected several inconsistent, awkward, or unclear phrases
- Ensured all keys and overall file structure remain unchanged
- Only zhCN and zhTW fields were modified
These translation updates were done by my friend（Ordin）, who is a native Chinese speaker.
Since he does not use GitHub, I’m submitting this pull request on his behalf to share his work with the community.
=> Fix and enhance zhCN & zhTW translations

data/local/lng/strings/item-runes.json
this name was updated at 2.1.0 release.
but other langauges still use `blood moon`.
related #809
=> KOR translation: `Searing Moon`

data/local/lng/strings/item-names.json
vanilla has it as just gibbet, somewhere along the way it got changed and is causing missing string
before
after
=> missing string fix
